### ISSUE TITLE
broken tooltip for undo/redo navbar buttons

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#568]
think it stems from combination of changes in d86722a98cff683f6294abbee2ca65facfb25631 and #561.

can be partly fixed by changing reference to translation to a function on line 96 of generator.js but that leaves us with an undefined hint .. haven't yet traced the source of the hint problem but it seems that maybe the keysAdded event isn't being called for the undo and redo keys?

**Comment by balmas** [comment]
@LFDM: this appears to be a scope thing (that I don't fully understand). The hist-undo and hist-redo directives have isolate scope and the broadcast of the keyAdded event on the rootScope doesn't have the listeners registered by the scope of the hist-undo and hist-redo directives (via generator).  It seems that moving the invocation of the keyCapture.initCapture method out of the init() method of the history plugin to the definition of the keys var of the history service has changed the scope in which it is invoked? If I compare this to saver, which also has an isolate scope and does get its keyAdded listener registered in the rootScope of the broadcast event, the difference seems to be this.  The change in #561 moved the history plugins definition of the keyCapture out of the init method but I am not really clear on if this was really necessary to fix #557 - was this causing the keyCapture callbacks to be registered multiple times?? Or was that just code refactoring for another reason?

**Comment by balmas** [comment]
Sorry for the stream-of-consciousness comments here, but maybe it's as good a way as any to have a record of things that come up for people trying to learn the arethusa code base..

Anyway, I see that the history service's init method is in fact called twice, from ArethusaCtrl's bootstrap method, and then again when the plugin inits. This isn't the case for saver, which is not itself a plugin.  

So it would be good to get an additional comment added to the ArethusaCtrl bootstrap code to explain why history has to be initialized separately here and not only through the iteration of plugins (I think you did mention this in the code review but I don't have it documented...)

**Comment by LFDM** [comment]
It's all much simpler - might respond to this in more detail tonight.

Sorry for the stream-of-consciousness comments here, but maybe it's as good
a way as any to have a record of things that come up for people trying to
learn the arethusa code base..

Anyway, I see that the history service's init method is in fact called
twice, from ArethusaCtrl's bootstrap method, and then again when the plugin
inits. This isn't the case for saver, which is not itself a plugin.

So it would be good to get an additional comment added to the ArethusaCtrl
bootstrap code to explain why history has to be initialized separately here
and not only through the iteration of plugins (I think you did mention this
in the code review but I don't have it documented...)

—
Reply to this email directly or view it on GitHub
<https://github.com/latin-language-toolkit/arethusa/issues/568#issuecomment-68507504>
.

**Comment by LFDM** [comment]
This was quite easily fixed through #570 eventually.

About your stream of consciousness - I think you were following a few wrong leads here, probably mainly a slight misconception of what _isolate scope_ in angular means and why `history` is init'ed several times (which is my bad, not a bug, but a little flawed)

- Isolate Scopes

You were eventually changing the `$on` listener to a `$watch` listener, which is the right thing to do in this case (cf. my comments to #569 and eventually the merged fix in #570), but it seems you did it for the wrong reason: A broadcast on `$rootScope` can **always** be seen by all scopes, including isolate scopes. Scopes in angular are a tree  with the `$rootScope` on top of it. A `$broadcast` sends an event down the tree hierarchy and will therefore reach each and every scope present in an application. It's is not necessary to define a listener with `$rootScope.$on` to have access to such events. `$rootScope` on can be used mainly for two things: 1) If a service, which naturally doesn't have a scope, wants to add a listener. It can then inject `$rootScope` and define its listener there. This is for example what plugins sometimes do - `state` is also delegating these event methods for easier access. A 2) option to use `$rootScope.$on` is a little more sophisticated and advanced (just referring to this for completeness). You can use it to use eventing on a top-level only, without going up or down a scope tree. If you `$rootScope.$emit` something, only listeners that have defined their `$on` directly on `$rootScope` will be notified. (I think I don't use this in Arethusa though)

Long story short: Isolate scopes do **NOT** differ in their `$on`/`$watch` behaviour from other scopes. Their isolation is defined by severing their *implicit* link to their parent scope. If a directive uses a child scope it has implicit *read* access to all of the parent scope's variables (achieved by passing `scope: true` in a directive definition). If a directive uses the parent scope (`scope: false`, or simply keeping it undefined) it has implicit *read* and *write* access to the parent scope.

An isolate scope has none of this. All accessible scope variables need to be passed *explicitly* to a directive with an isolate scope (by using the `scope` definition object with the funny identifiers `=`, `&` and `@`).

Note that an explicit access to a parent scope is still available to all directives by looking at `scope.$parent`.



Moving the definition of history keybindings out of its `init` function had no effect on scoping whatsoever - the application is not that complex ;)

`init` functions are just a common name for a function exposed by a service, so that a service like `plugins` has a common function to call. There is no scoping magic going on here.

I think what you most likely did here is putting regular javascript scopes and angular scopes in one basket. They are of course conceptually the same, but angular's scopes have apart from that not much common with javascript function scopes. Angular scopes are used to give controlled access javascript code inside the DOM - they are first and foremost concerned with templating.


- Why `init` of `history` is called several times

I am unnecessarily causing confusion here by breaking some Arethusa concepts with the `history` plugin.

`history` is different than all others, it's something like a hybrid and is both a `core` service as well as a `plugin`. This shows itself in several ways:

- The built mechanisms have it included in the `core` of Arethusa (`arethusa.min.js`).
- The module is injected right away into `arethusa` - no other plugin is handled that way.
- The `history` service is injected into the `ArethusaCtrl` - no other plugin is handled that way.


This was done to have `history` accessible at all times (meaning: basic undo/redo functionality as well as the option to inject the `history` service anywhere to gain access to the history of all state events everywhere [not used anywhere right now - was done for a future feature, which is always a bad bad move, cf. [YAGNI](http://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it))

Only when `history` is *also* used as a plugin, `history` shows up as an own tab in e.g. the Sidepanel layouts.

78b2750 was absolutely needed to fix #557. When `history` is used as a plugin, `plugins` will call a plugin's `init` function everytime a chunk move is performed. As the keybindings were defined inside of `init` we were adding new keybindings for undo/redo all the time - totally messing up this funcitonality. E.g. after you have moved chunks for three times, hitting the undo keybinding once, would have undone 4 changes - as this keybinding was all in all defined four times (once by `ArethusaCtrl` and three times by `plugins`, which called `history.init`)

But we only want to do this once - we therefore moved it to the function body of the `history` service itself.

This change led to the bug regarding the hints as outlined in this issue. This had nothing to do with scoping as I already mentioned, but with the **time** at which the original `keysAdded` event was fired (this event triggered the definition of the key hint before, which has now changed in #570)

`history` is an angular `service`, which is basically just a wrapper around angular's `provider` functionality. Through this angular allows that any angular clas, such as a service, is lazily loaded the first time the runtime code needs access to such a thing.

As `ArethusaCtrl` is injecting `history`, which is the first appearance of this `service` inside of Artehusa. The function body (which contains the definition of the keybindings) is therefore exectuted at a  very very early time in the application. In fact - it is one of the very first things to run and runs even **before** the template of this `ArethusaCtrl` is inserted into the DOM (the template which is defined by the `main` route [here](https://github.com/latin-language-toolkit/arethusa/blob/18043a425dfade2c4af892d06753e5d14d4e1dd5/app/js/arethusa.core/routes/main.js). If you look at this template you can see that it also includes the `arethusa-navbar` directive, which will eventually hold the `history-undo` and `history-redo` directives.

This means that when `history` is defining its keyCaptures, the `history` directives are **not yet** present. When `keyCapture` is firing `keysAdded` events through the scope hierarchy, the `history` directives cannot listen - they are just not there in the moment this is happening. 

So this is not a problem of *scoping*, but of *timing* - the `keysAdded` event is not suited to handle this properly, that's why the change merged in #570 was a good one.

**Comment by balmas** [comment]
Excellent explanation. Vielen Dank!
