### ISSUE TITLE
assigned token ids should be cleared when document is reloaded via change in the url param

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#592]
Reported by @gcelano

I'm not sure if this is a bug introduced by ce85c114e9e827f0744348c4cdcbba3457662eb3 or a symptom of the problem it was designed to catch, but the assigned source ids object in id_handler.map is not cleared if a document is loaded in response to a manual change in the chunk param in the url.

e.g. load a document and rather than using the navigator to navigate to a different sentence, change the value of the chunk param in the url in the browser location bar and press enter. This results in a partial reloaded only of the Arethusa code ( a known issue ) and then the id_handler starts reporting errors as it tries to reassign source ids that are already assigned.

**Comment by LFDM** [comment]
The problem is in this case Angular's nature as a single page app. State persists through route changes, apart from everything that's only defined in a scope. Everything service related is a persistant singleton and remains.

This could be seen to some degree as design flaw in Arethusa - on the other hand it's not really meant to be that people change routes themselves. The workaround for this is to listen for route changes and trigger a full page reload then. From the top of my head I don't now though if there's a stable API across browsers to trigger this.

**Comment by balmas** [comment]
@LFDM just quickly -- I agree we don't need to generally handle this problem of changing urls, but would like not to throw errors in this case - so whatever code is causing the document reloading to happen, even if it's only partial, should be clearing out the map of assigned sourceids.  Not sure if this is actually the lingering bug you were worried about when you first reviewed the id_handler changes for this or not?
