### ISSUE TITLE
nav bar looks really lousy with long document ids

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#595]
See attached
![screenshot from 2015-01-19 17 58 24](https://cloud.githubusercontent.com/assets/644870/5809279/e4f69518-a004-11e4-8135-24432ac9e672.png)

**Comment by LFDM** [comment]
The navbar is usually adjusting to different sizes and has collapsible behaviour built in. The thresholds for this can be found in the `arethusaNavbar` and the `navbarButtons` directive. The latter is what we need to fix here.

The problem is that the thresholds are currently hardcoded to pixel sizes of the whole screen and do not take such a long element as long document ids into account. Is probably a bit tricky to do really right, the easiest workaround would be to check for the char length of such strings and once this gets too high use the collapsed template instead of the expanded one.

**Comment by LFDM** [comment]
We could also just totally take out the unused `Search for documents` field - it's actually funny that no one has ever argued about this - it's completely not functional, or better: Something can be done with it, but I guess no one knows what and it's therefore never used anyway.

This would give us quite some breathing space.

**Comment by balmas** [comment]
Hmm. actually I just realized the other day that this really does work if you know the identifier of the document you want to load.  This could actually be quite useful with a little more work on the Perseids back-end to support it.

**Comment by LFDM** [comment]
Ah so at least one person figured out what to do with this :)

But yes, this was the initial plan, I think I mentioned this at some point already. Christof and I wanted to have a magic search box - but never got to implement it.

The idea is to have a modular search system there, which can hunt for various things:
- Other documents, which would require a response from a backend
- Document-wide full text search at least

It's not that hard to implement from the Arethusa side I think.

From the Perseids backend we would probably need just one single endpoint, which we start to query once a user starts to type something into this search box. A response like:

```javascript
[
  "docIdentifier" : {
    // one or several fields with strings that make some sense, such as the authors name or other keywords
  }
  ...
]
```
would be already sufficient...

**Comment by LFDM** [comment]
FYI this is still not 100% well - below 1000px not so nice things will happen, but i guess that's something which doesn't make much sense to optimize for anyway.
